Zp/poetry packaging
prob-ml/bliss pull request #166
Opened 2021-01-04 21:26 UTC by ZachariahPang

Close #165 

- Remove `bliss/bin` directory
- Move executables to `bliss/bliss`
- Instead of cd to the correct directory to run executables, now we can run
`poetry install` only for once to update the scripts in `bliss/bliss`
and run scripts from anywhere using `poetry run`
- For now, only `tune.py`,  `generate.py`, `train.py` are managed

eg. 
```shell
poetry run generate
```
or
```shell
poetry run tune model=m2 dataset=m2 training=m2 optimizer=m2 tuning.n_epochs=20
```

2021-01-04 21:40 UTC, ZachariahPang commented
I renamed `tuning.py` to tune.py to be consistent with the other executable names, `train.py` and `generate.py`, but this seems to also remove @zzhaozhe-profolio's editing history on that file.  Is there any work around?

2021-01-04 21:48 UTC, jeff-regier commented
`tune.py` is a good name. I'm not sure about the editing history; it looks to me like git recorded it as name change rather than a delete+add.

2021-01-04 21:54 UTC, ZachariahPang commented
> `tune.py` is a good name. I'm not sure about the editing history; it looks to me like git recorded it as name change rather than a delete+add.

It only shows me in git blame. It seems the problem is that I accidentally split the deleting and adding into two commits.
I'll force push a new history to this PR. Sorry about the inconvenience.

2021-01-04 21:57 UTC, jeff-regier requested changes
Looks great! Would you add simple unit tests that runs the code in `tune.py`? No need to check the output--just verify it runs. You might set n_epoch=1 so it finishes quickly even on a CPU.

2021-01-05 00:38 UTC, jeff-regier approved these changes
Lgtm!

2021-01-05 00:46 UTC, zzhaozhe-profolio commented on tests/test_tune.py
> +            "tuning.n_epochs": 2 if devices.use_cuda else 1,
I think both gpu and cpu only run 1 epoch would be fine

2021-01-05 00:48 UTC, zzhaozhe-profolio approved these changes

2021-01-05 01:00 UTC, merged