Bl klqp flux module
prob-ml/bliss pull request #281
Opened 2021-07-20 19:02 UTC by Runjing-Liu120

Hi Ismael, 

Here is a pull request that implements the module to train the flux encoder. I put this module in bliss/models/flux_net.py, and you can see how it works in this notebook [here](https://github.com/prob-ml/bliss/blob/bl-klqp-flux-module/case_studies/flux_module/flux_module_sandbox.ipynb). 

As you can see, it trains with all the default parameters you use for the sdss measurement; that is, the cfg overrides are: 

`overrides = {'model':"sleep_sdss_measure_simple", 'dataset':'default'}
`

I'm happy to set up a time to walk through the code. But I hope it should be fairly straightforward. For your metrics, I assume they take as input the current SleepNet estimates. You would now just replace the current SleepNet-estimated fluxes with the new flux encoder fluxes: that is, 

```
out = flux_encoder(images)

estimated_fluxes = out['mean']
```

and `out['mean']` should have the same data structure (a tensor of shape `n_images x n_tiles_per_image x max_sources x n_bands`) as the old fluxes out-putted by StarNet. 

Let me know if you have any comments on the code!

2021-07-21 15:08 UTC, ismael-mendoza reviewed
Thanks @Runjing-Liu120 for working on this ! I have a couple of comments below

2021-07-22 16:25 UTC, Runjing-Liu120 commented on bliss/models/flux_net.py
> +            raise NotImplementedError()
yes, lets leave the code to estimate fluxes in SleepNet as well -- as in, let's not get rid of the SleepNet fluxes just yet. We can view this new module as an alternative way to estimate fluxes

2021-07-23 16:35 UTC, ismael-mendoza requested changes
Hi @Runjing-Liu120 this looks basically ready to merge after a couple of small changes that we can go over in our meeting. :)

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/encoder.py
> +    with a sliding window=self.ptile_slen and stride=self.tile_slen
Just a small typo 

```suggestion
    with a sliding window=ptile_slen and stride=tile_slen
```

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +    # trim_slen x trim_slen pixels
```suggestion
    # crops an image so only the central `trim_slen x trim_slen` pixels remain.
```

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +    indx0 = int(np.floor(diff / 2))
Is this the same? 

```suggestion
    indx0 = diff // 2
```

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +def _trim_images(images, trim_slen):
Since this is a simple function I think you can remove extra spaces between lines inside this function

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +        latent_dim = 64
would you make this changeable or is 64 the best to use in general?

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +        h = F.relu(self.fc4(h))
Is there a reason to not combine all these statements into `nn.Sequential`?

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +
```suggestion
```

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +
```suggestion
```

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +        # the size of the ptiles passed to this encoder
```suggestion
        # padded tiles are trimmed to this size for the flux encoder
```

2021-07-23 16:35 UTC, ismael-mendoza commented on bliss/models/flux_net.py
> +        kl = self.kl_qp_flux_loss(batch, out["samples"], out["sd"])[0]
```suggestion
        kl, _ = self.kl_qp_flux_loss(batch, out["samples"], out["sd"])
```

2021-07-27 17:30 UTC, jeff-regier commented
Hi, It looks like the CI status check is failing just because of some formatting issues:
```
bliss/models/flux_net.py:21:0: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:28:22: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:29:31: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:30:29: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:31:35: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:32:27: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:33:31: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:57:0: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:58:30: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:71:0: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:73:48: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:75:46: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:77:46: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:81:0: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:113:0: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:116:0: C0303: Trailing whitespace (trailing-whitespace)
bliss/models/flux_net.py:1:0: W0611: Unused numpy imported as np (unused-import)
```

Have you run `pre-commit install`?

2021-07-28 20:32 UTC, merged