add coadd_decoder, examples_ and test_
prob-ml/bliss pull request #656
Opened 2022-07-29 23:07 UTC by wangmallory

add coadd_decoder, examples_coadd_decoder and test_coadd_decoder

2022-08-01 18:22 UTC, wangmallory commented
@ismael-mendoza I'm getting a test failure for `test_multiple_sources_one_tile` but I did not make any changes to this test.

2022-08-08 19:19 UTC, ismael-mendoza requested changes

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        weight = 1 / torch.tensor(aligned_images)
I think you want the weight to be ($I_{i}$ is the noiseless aligned image) 

![Screen Shot 2022-08-08 at 14 51 27](https://user-images.githubusercontent.com/11745764/183492170-aaae5284-95de-4434-a15c-1a5a2b550c7b.png)

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +    return num / (torch.sum(weight, dim=0))
![Screen Shot 2022-08-08 at 15 08 25](https://user-images.githubusercontent.com/11745764/183495108-dd6785ce-6f35-4a49-910c-4df26e2da52f.png)

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        snr_images = get_snr(aligned_images_nobackground, background)
```suggestion
```

we dont' need SNR because we are using weights

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        )
try to split this statement into multiple statements that each fit in one line (with e.g. temporary variables)

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        )
```suggestion
        aligned_images_nobackground = rearrange(aligned_images, 'd h w -> d 1 h w')
```

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +            image0[:].reshape(size, size), noiseless, size, dithers
```suggestion
            image0.reshape(size, size), noiseless, size, dithers
```

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        full_cat["background"] = background
```suggestion
```

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +            "snr_images": snr_images,
```suggestion
```

2022-08-08 19:19 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +            "coadded_image": coadded_image,
```suggestion
            "images": coadded_image,
```

2022-08-09 00:10 UTC, wangmallory commented on case_studies/coadds/coadd_decoder.py
> +        shift = shift.reshape(1, 2) if len(shift) == 2 else shift
I think `torch.add` and `t1 + t2` are the same.

2022-08-10 17:17 UTC, wangmallory commented
@ismael-mendoza I think I covered all the revisions except for the configuring `CoaddGalsimBlend` directly in the test file

2022-08-12 15:43 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        shift = shift.reshape(1, 2) if len(shift) == 2 else shift
might be easier to just use `t1+t2` in the future

2022-08-12 18:42 UTC, ismael-mendoza requested changes
Looks like it's really close :) Just couple more suggestions and I think we can merge

2022-08-12 18:42 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        dithers = dithers.reshape(num_dithers, 2)
You can simplify this a lot with `super()`
```suggestion
        d = super().sample()
        d['dithers] = torch.distributions.uniform.Uniform(-0.5, 0.5).sample([num_dithers,2])
        return d
```

2022-08-12 18:42 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        }
```suggestion
```

2022-08-12 18:42 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        #        image0 = rearrange(image0, "1 1 h w -> h w")
```suggestion
```

2022-08-12 18:42 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        ) = self._get_images(full_cat, dithers)
is there a way you can avoid this? for example: 
```
noiseless, _, _, background, coadded_image = self._get_images(full_cat, dithers)
```

2022-08-12 18:42 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        full_cat = self._add_metrics(full_cat, noiseless, background, coadded_image)
You forgot the `tile_params` in the original dataset: 

```suggestion
        full_cat = self._add_metrics(full_cat, noiseless, background, coadded_image)
        tile_params = self._get_tile_params(full_cat)
```

2022-08-12 18:42 UTC, ismael-mendoza commented on case_studies/coadds/coadd_decoder.py
> +        }
```suggestion
        return {
            "noiseless": noiseless,
            "background": background,
            "images": coadded_image,
            **tile_params
        }
```

2022-08-13 18:33 UTC, wangmallory commented on case_studies/coadds/align_single_exposures.py
> +    interped_images = rearrange(interped_images[:][0].clone().detach(), "d 1 h w -> d h w")
I don't know why I added this. :/ Thanks for catching.

2022-08-16 19:51 UTC, merged